### PR TITLE
[ADD]add src/evaluate/generate_plot/generate_plot.py and corresponding

### PR DESCRIPTION
**Pull request by happy91512**
library src/evaluate/generate_plot/Useful_Tools_for_Me.

### CODE REVIEW

**Comment by tw-yshuang** [comment]
I already have duplicated submodules. Please remove the duplicate parts. Thanks!

**Comment by happy91512** [comment]
move src/evaluate/generate_plot/generate_plot.py to src/evaluate/generate_plot.py

**Comment by tw-yshuang** [comment]
great job~~

**Comment by happy91512** [comment]
I remove an useless folder.

**Comment by tw-yshuang** [comment]
Thanks.

**Pull request merged**
